find_package(PackageHandleStandardArgs)

find_library(CLBLAS_LIBRARY clBLAS)
get_filename_component(CLBLAS_LIBRARY_DIR ${CLBLAS_LIBRARY} PATH)
find_path(CLBLAS_INCLUDE_DIR clBLAS.h ${CLBLAS_LIBRARY_DIR}/../include)

if(NOT CLBLAS_INCLUDE_DIR)
    set(CLBLAS_LIBRARY CLBLAS_LIBRARY-NOTFOUND)

    find_library(CLBLAS_LIBRARY clBLAS ENV LD_LIBRARY_PATH NO_DEFAULT_PATH)
    get_filename_component(CLBLAS_LIBRARY_DIR ${CLBLAS_LIBRARY} PATH)
    find_path(CLBLAS_INCLUDE_DIR clBLAS.h ${CLBLAS_LIBRARY_DIR}/../include)
endif()

if(NOT CLBLAS_INCLUDE_DIR)
    set(CLBLAS_LIBRARY CLBLAS_LIBRARY-NOTFOUND)

    find_library(CLBLAS_LIBRARY clBLAS $ENV{AMDAPPBLASSDKROOT}/lib NO_DEFAULT_PATH)
    get_filename_component(CLBLAS_LIBRARY_DIR ${CLBLAS_LIBRARY} PATH)
    find_path(CLBLAS_INCLUDE_DIR clBLAS.h ${CLBLAS_LIBRARY_DIR}/../include)
endif()

find_package_handle_standard_args(clBLAS REQUIRED_VARS CLBLAS_LIBRARY CLBLAS_INCLUDE_DIR)

if(CLBLAS_FOUND)
    set(CLBLAS_LIBRARIES ${CLBLAS_LIBRARY})
    set(CLBLAS_INCLUDE_DIRS ${CLBLAS_INCLUDE_DIR})
endif()

mark_as_advanced(CLBLAS_LIBRARY CLBLAS_LIBRARY_DIR CLBLAS_INCLUDE_DIR LIB64)
